apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
data:
  aws-bucket: YXJuOmF3czpzMzo6OmVrcy1idWNrZXQtMzg0MjIzNjE4ODMy
  aws-profile: ZGVmYXVsdA==
  aws-region: dXMtd2VzdC0y
  aws-access-key-id: QUtJQVZTNU1ERTRJREJIVjVHR1Y=
  aws-access-key-secret: VmQ2SHNibXMzZTNwUWFudkgwNzkrdHVWREZVN2JWYlFEV2lkcEFEbA==