apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: idankouadjo/udagram-api-user:v1
        ports:
        - containerPort: 8082
        env:
          - name: AWS_BUCKET
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws-bucket
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws-bucket
          - name: AWS_PROFILE
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws-bucket
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres-password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres-database
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres-host
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: jwt-secret
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: url