apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: idankouadjo/reverseproxy:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: AWS_BUCKET
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws-bucket
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws-bucket
          - name: AWS_PROFILE
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws-bucket
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres-password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres-database
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres-host
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: jwt-secret
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: url
    restartPolicy: Always