version: 2.1
orbs:
  docker: circleci/docker@1.7.0 
jobs:
  feed-job:
    docker:
      # replace with your preferred image
      - image: cimg/node:13
    steps:
      - docker/build:
          image: udagram-api-feed 
          path: ./udagram-api-feed 
          tag: v1 
          dockerfile: Dockerfile 

workflows:
  version: 2.1
  example-workflow:
    jobs:
      - feed-job