version: 2
orbs:
  docker: circleci/docker@1.7.0      
jobs:
  build:
    docker:
      # replace with your preferred image
      - image: cimg/node:13
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: 
              docker build -t udagram-api-feed ./udagram-api-feed
      - run:
          command:
              docker tag udagram-api-feed idankouadjo/udagram-api-feed:v1
      - run:
          name: Push images to docker hub
          command:
              echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
      - run:
          command:
              docker push idankouadjo/udagram-api-feed:v1

workflows:
  version: 2
  udagram-workflow:
    jobs:
      - build