version: 2.1
orbs:
  docker: circleci/docker@1.7.0      
jobs:
  backend-feed-job:
    docker:
      # replace with your preferred image
      - image: circleci/node:13
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - docker/build:
          image: udagram-api-feed
          path: ./udagram-api-feed
      - docker/push:
          image: idankouadjo/udagram-api-feed

  backend-user-job:
    docker:
      - image: circleci/node:13
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - docker/build:
          image: udagram-api-user
          path: ./udagram-api-user

  reverseproxy-job:
    docker:
      - image: circleci/nginx:alpine
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - docker/build:
          image: reverseproxy
          path: ./udagram-reverseproxy
  frontend-job:
    docker:
      - image: circleci/node:13
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - docker/build:
          image: udagram-frontend
          path: ./udagram-frontend
workflows:
  udagram-workflow:
    jobs:
      - backend-feed-job
      - backend-user-job
      - reverseproxy-job
      - frontend-job